spring:
  application.name: historyservice-project
  profiles.active: local

spring.data.mongodb.uri: ${MONGO_URI:mongodb://localhost:27017/historyservice}

---
spring:
  profiles: local

server:
  port: 9000
  servlet.context-path: /historyservice